# Generated by Django 5.0.7 on 2024-07-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kind',
            field=models.CharField(choices=[('1', 'worker'), ('2', 'supervisor')], default=1, max_length=200),
        ),
    ]
