# Generated by Django 5.0.7 on 2024-07-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0008_alter_assign_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
