# Generated by Django 5.0.7 on 2024-07-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0009_task_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assign',
            options={'ordering': ['-done_at']},
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
